# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 984ece74abe4e06a3927cc3aac945a03e088b08ccd625219ea8d377a8d4a8e06b685fcd60c3388349e2d2d7afc5577d6b2deb787dbccb1b65f9fce16f1c8507a

test:
  secret_key_base: befd3789081a79e61bc4c70a595f00c8e4bd04ace8d8ebd6fbd833c48e580795cf4a408a7fa077d61f0d8d3ff4b585bbed3bc446c3f38f44d1356bbbe7e44531

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
